### ISSUE TITLE
Deploy project

### ISSUE THREAD

**Issue by Mkadir** [vsdudakov/fastadmin#41]
Could you show example to deploy fastadmin server through uvicorn, nginx, apache ?

**Comment by WrldEngine** [comment]
**Fastadmin should be added to your project as application**

To deploy with unicorn:
- `uvicorn main:app --host 0.0.0.0 --port 80`

Nginx deployment:
- https://unit.nginx.org/howto/fastapi/

apache deployment:
- https://github.com/tiangolo/fastapi/issues/3431

**Comment by vsdudakov** [comment]
Looks like we can close the issue.

**Comment by WrldEngine** [comment]
> Looks like we can close the issue.

Why my response not marked as answer, if you close the issue? I don't know github very well
