### ISSUE TITLE
Foreign id's don't display

### ISSUE THREAD

**Issue by samy38** [vsdudakov/fastadmin#48]
Hello,

I'm using your application with fastapi + sqlalchemy

I have 2 tables:

```
Reservation
   id
Transaction
  id
  reservation_id (foreignkey to reservation.id)
```

I declare a TransactionAdmin like that for my transaction:
```

@register(Transaction, sqlalchemy_sessionmaker=sqlalchemy_sessionmaker)
class TransactionAdmin(SqlAlchemyModelAdmin):
    list_display = (
        "id",
        "reservation_id",
    )
    raw_id_fields = ("reservation_id", )


```

In the table or in the detail reservation_id is never shown. :(

When i watch the api call to get my transactions, reservation_id is not included in the json.

**Comment by solfrii** [comment]
@samy38 I guess you need to use
```python
raw_id_fields = ("reservation", )
```
(without `_id` suffix)

Have updated [FastAPI + SQLAlchemy 2.x example](https://github.com/vsdudakov/fastadmin/blob/0812185d7f052b2a4daf42917d888176b6ccfa84/examples/fastapi_sqlalchemy/example.py#L86)

**Comment by samy38** [comment]
ok, it works now. :)

Thanks.
