### ISSUE TITLE
automatic hash password during creation record

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#68]
I've been developing project with your admin panel with fastapi+sqlAlchemy
and I can't understand how I can do this in fastAdmin

I see authenticate method and change_password method, but no word about this

In documentation I noticed "password": (WidgetType.PasswordInput, {"passwordModalForm": True}),
but when I try to create record, I don't see password field and 
After sending data, I catch error from sqlAlchemy with NoneType in password field

fieldsets = (
        (None, {
            "fields": (
                "role",
                "firstName",
                "secondName",
                "email",
                "phone",
                "password"
            )
        }),
    )
    formfield_overrides = {  # noqa: RUF012
        "role": (WidgetType.Select, {"required": True}),
        "firstName": (WidgetType.SlugInput, {"required": True}),
        "secondName": (WidgetType.SlugInput, {"required": True}),
        "email": (WidgetType.EmailInput, {"required": False}),
        "phone": (WidgetType.PhoneInput, {"required": True}),
        "password": (WidgetType.PasswordInput, {"passwordModalForm": True}),
    }

**Comment by matv864** [comment]
sorry, I found out I can't read
I write exclude password and don't see it

**Comment by matv864** [comment]
I've been developing project with your admin panel with fastapi+sqlAlchemy
and I can't understand how I can do this in fastAdmin

I see authenticate method and change_password method, but no word about this

**Comment by vsdudakov** [comment]
@matv864 do you still have an issue?

**Comment by matv864** [comment]
> @matv864 do you still have an issue?

Yes, Could you add information in documentation about automatic hashing or where "change_password" is used?

**Comment by reouno** [comment]
@vsdudakov Hi, I have the same issue in fastapi+sqlAlchemy.
I defined "change_password" according to the documentation but the UI is not shown in admin UI.
I would like to know how and where "change_password" is used.

**Comment by LPJWS** [comment]
Same, I defined change_password but there is no UI for this

**Comment by vsdudakov** [comment]
https://github.com/vsdudakov/fastadmin/pull/78/files
