### ISSUE TITLE
deserialize_value

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#69]
I'm developing project with fastadmin. And I need to add foreign key. Code understood type of field and raw_id_fields

![image](https://github.com/user-attachments/assets/0d9c412f-893c-49af-839f-2978934dbeb9)

but function deserialize_value don't know what is raw_id mean

![image](https://github.com/user-attachments/assets/31d4aa7b-4f48-4500-b5e4-18dc0912c9ad)

what about add pydantic by optional or add code here to handle more data types?

**Comment by matv864** [comment]
I saw closed issue about removing pydantic, but what about making it by otional
![image](https://github.com/user-attachments/assets/f067c88d-2773-48cb-aed1-e0ffcf15e9a7)
![image](https://github.com/user-attachments/assets/2e2485ed-67ef-4f65-afa3-4d185bb96420)

**Comment by vsdudakov** [comment]
good catch  - I will fix

**Comment by vsdudakov** [comment]
I cannot reproduce with sqlite  - will try with postgrtesql
could you send me traceback from dev server run of 500

**Comment by vsdudakov** [comment]
Probably it could be fixed here https://github.com/vsdudakov/fastadmin/releases/tag/0.2.17
