### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#70]
in FastAdmin you are using asynchronous approach
but functions which manage permissions is synchronous and python don't allow throw async request to database
please fix to async
![image](https://github.com/user-attachments/assets/c75975ba-1a6c-428e-a2e5-30db4f0d9581)
![image](https://github.com/user-attachments/assets/c10d4ed1-eef5-4e2b-a17b-b4e228d745ba)

**Comment by vsdudakov** [comment]
ok let me fix it

**Comment by matv864** [comment]
@vsdudakov 
I tried to fix this problem and I sent pull request with fixing this
please look at him

**Comment by vsdudakov** [comment]
Merged PR. @matv864 thanks for the PR. I will; release it
