### ISSUE TITLE
Problem to edit

### ISSUE THREAD

**Issue by HadeSxGod1337** [vsdudakov/fastadmin#71]
Hello! 
A similar error occurred as https://github.com/vsdudakov/fastadmin/issues/65
Using: fastapi==0.111.1
SQLAlchemy==2.0.34
## base.py
from sqlalchemy.types import DateTime
from typing import Optional
from sqlalchemy import MetaData

from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from datetime import datetime

class BaseModel(DeclarativeBase):
    metadata = MetaData(
        naming_convention={
            "ix": "ix_%(column_0_label)s",
            "uq": "uq_%(table_name)s_%(column_0_name)s",
            "ck": "ck_%(table_name)s_`%(constraint_name)s`",
            "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
            "pk": "pk_%(table_name)s",
        }
    )

    created_at: Mapped[Optional[str]] = mapped_column(default=datetime.now, type_=DateTime)
    updated_at: Mapped[Optional[str]] = mapped_column(default=datetime.now, onupdate=datetime.now, type_=DateTime)

##foo.py

from uuid import uuid4, UUID
from sqlalchemy.orm import Mapped, mapped_column
from .base import BaseModel

class FooModel(BaseModel):
    __tablename__ = "foo"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4())
    name: Mapped[str]
    
## admin/models/foo.py

from fastadmin import SqlAlchemyModelAdmin, register

from app.models.foo import FooModel

from app.database import sessionmanager

@register(FooModel, sqlalchemy_sessionmaker=sessionmanager._sessionmaker)
class FooAdmin(SqlAlchemyModelAdmin):
    list_display = ("id", "name")
    list_display_links = ("id", "name")
    list_filter = ("id", "name")
    search_fields = ("name",)

**Comment by HadeSxGod1337** [comment]
If I don't specify the "created_at" and "updated_at" fields in fieldsets, then the edit page opens

**Comment by matv864** [comment]
What exactly is the problem?
I saw problem with JS console, but what's the problem on admin panel?

**Comment by HadeSxGod1337** [comment]
> What exactly is the problem? I saw problem with JS console, but what's the problem on admin panel?

Similarly https://github.com/vsdudakov/fastadmin/issues/65, the edit page does not open

**Comment by matv864** [comment]
I saw this, but I suppose it is type of date field

I change 
your line
created_at: Mapped[Optional[str]] = mapped_column(default=datetime.now, type_=DateTime)
to my
created_at: Mapped[datetime] = mapped_column(TIMESTAMP, default=datetime.now)

and it's work

**Comment by HadeSxGod1337** [comment]
> I saw this, but I suppose it is type of date field
> 
> I change your line created_at: Mapped[Optional[str]] = mapped_column(default=datetime.now, type_=DateTime) to my created_at: Mapped[datetime] = mapped_column(TIMESTAMP, default=datetime.now)
> 
> and it's work

Thank you very much!

**Comment by HadeSxGod1337** [comment]
https://github.com/vsdudakov/fastadmin/issues/71#issuecomment-2389182676
