### ISSUE TITLE
upload objects

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#72]
I want to create uploading objects. I see what I can upload a lot of objects, but I see one base64-string
how I can get all objects from base64 string?
how I can decode this base64-string?

![image](https://github.com/user-attachments/assets/8d095c4d-4835-47cd-9675-6e292a43335b)

**Comment by matv864** [comment]
but can I override uploading objects and take a lot of files from base64?
or you can make base64 only from one file?

**Comment by vsdudakov** [comment]
I'm going to close the issue. Please reopen if you need any help
