### ISSUE TITLE
upload objects and save model

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#73]
![image](https://github.com/user-attachments/assets/9e6f9a73-a42c-40b2-bcce-7b72ea9b4d9e)
I try to upload object, but when I change field in model, model don't save changing
what about 
upload function before saving model?

my crutch
![image](https://github.com/user-attachments/assets/48fa3cd3-e988-4a16-9221-c7f8cc2966d0)

**Comment by matv864** [comment]
it's work and work very good

**Comment by vsdudakov** [comment]
See example for django

```
    @sync_to_async
    def orm_save_upload_field(self, obj: Any, field: str, base64: str) -> None:
        """This method is used to save upload field.

        :params obj: an object.
        :params field: a m2m field name.
        :params base64: a base64 string.

        :return: A list of ids.
        """
        from django.core.files.base import ContentFile

        _format, _img_str = base64.split(";base64,")
        _name, ext = _format.split("/")
        name = _name.split(":")[-1]
        name = f"{name}.{ext}"
        data = ContentFile(b64decode(_img_str), name=name)
        getattr(obj, field).save(name, data, save=True)
```

getattr(obj, field).save(name, data, save=True)

to be universal for all orms you have to save the uri to table field separately in this function (it is awaitable for sqlalchemy)

**Comment by vsdudakov** [comment]
Please reopen if you still have questions

**Comment by vsdudakov** [comment]
async def orm_save_upload_field(self, obj: Any, field: str, base64: str) -> None:

you have obj in the function. 
You have to save uri/path to table column here in this function if you need
