### ISSUE TITLE
deleting objects

### ISSUE THREAD

**Issue by matv864** [vsdudakov/fastadmin#74]
![image](https://github.com/user-attachments/assets/311a4a78-5c7d-48b6-b2ea-5dd48103e639)

ORM: SQLAlchemy
need to delete files from upload fields

**Comment by vsdudakov** [comment]
If you need to have this additional logic please overload orm_delete_obj function in your Model
async def orm_delete_obj(self, id: UUID | int) -> None:
   # do it in one transaction
   remove file from storage s3 or other storage
   await super(self).orm_delete_obj(id)
