### ISSUE TITLE
Disable crop on Upload

### ISSUE THREAD

**Issue by LPJWS** [vsdudakov/fastadmin#79]
I need to make image upload field but i don't need a crop this. How to disable it?
![image](https://github.com/user-attachments/assets/7bfa28e1-3f2e-4caa-a12f-037bde9f51bc)

**Comment by vsdudakov** [comment]
No way for now. I will add env var to disable it today

**Comment by vsdudakov** [comment]
@LPJWS fixed here https://github.com/vsdudakov/fastadmin/releases/tag/0.2.16

**Comment by vsdudakov** [comment]
Use env var ADMIN_DISABLE_CROP_IMAGE=True to disable cropping
