### ISSUE TITLE
[SQLAlchemy Update ]

### ISSUE THREAD

**Issue by Rustam95Ur** [vsdudakov/fastadmin#84]
I get an error when updating a record

```
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\fastadmin\models\base.py", line 466, in save_model
    return await self.serialize_obj(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\fastadmin\models\base.py", line 371, in serialize_obj
    obj_dict.update(await self.serialize_obj_attributes(obj, attributes_to_serizalize))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\fastadmin\models\base.py", line 341, in serialize_obj_attributes
    serialized_dict = {field.name: getattr(obj, field.column_name) for field in attributes_to_serizalize}
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\fastadmin\models\base.py", line 341, in <dictcomp>
    serialized_dict = {field.name: getattr(obj, field.column_name) for field in attributes_to_serizalize}
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\sqlalchemy\orm\attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\sqlalchemy\orm\state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "C:\Users\Admin\AppData\Local\pypoetry\Cache\virtualenvs\cybro-dapp-api-6i6tLQRz-py3.11\Lib\site-packages\sqlalchemy\orm\loading.py", line 1603, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Fund at 0x1fab329d3d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```

My class

```
@register(Fund)
class FundAdmin(SqlAlchemyModelAdmin):
    list_display = ("id", "name", "is_visible")
    list_display_links = ("name",)
    ordering = ("name",)
    list_filter = (
        "tvl_type",
        "fund_type",
        "is_visible",
    )
    search_fields = ("name",)
    db_session_maker = sqlalchemy_session_maker
    fieldsets = (
        (
            None,
            {
                "fields": (
                    "name",
                    "description",
                    "icon",
                    "points",
                )
            },
        ),
        (
            "Contract data",
            {
                "fields": (
                    "address",
                )
            },
        ),
    )
```
I also get this error only with this class. What could be the reason for this?

**Comment by vsdudakov** [comment]
According to documentation you probably need 
@register(Fund, sqlalchemy_sessionmaker=sqlalchemy_session_maker) instead @register(Fund) and remove db_session_maker = sqlalchemy_session_maker here

**Comment by Rustam95Ur** [comment]
@register(Fund, sqlalchemy_sessionmaker=sqlalchemy_session_maker)

Same error. 
![image](https://github.com/user-attachments/assets/71eeda2d-1341-4dd4-970b-29aef36c3a41)


The solution with updating the code in the functions serialize_obj_attributes and serialize_obj helped

**Comment by Rustam95Ur** [comment]
`    async def serialize_obj(self, obj: Any, list_view: bool = False) -> dict:
        """Serialize orm model obj to dict.

        :params obj: an object.
        :params exclude_fields: a list of fields to exclude.
        :return: A dict.
        """
        fields = self.get_model_fields_with_widget_types()
        fields_for_serialize = self.get_fields_for_serialize()

        obj_dict = {}
        attributes_to_serizalize = []
        for field in fields:
            if field.name not in fields_for_serialize:
                continue
            if field.is_m2m and list_view:
                continue
            if field.is_m2m:
                obj_dict[field.name] = await self.orm_get_m2m_ids(
                    obj, field.column_name
                )
            else:
                attributes_to_serizalize.append(field)

        session_maker = self.get_sessionmaker()

        async with session_maker() as session:
            await session.merge(obj)

            obj_dict.update(
                await self.serialize_obj_attributes(
                    obj, attributes_to_serizalize, session=session
                )
            )

            for field_name in fields_for_serialize:
                display_field_function = getattr(self, field_name, None)
                if not display_field_function or not hasattr(
                    display_field_function, "is_display"
                ):
                    continue

                if inspect.iscoroutinefunction(display_field_function):
                    display_field_function_fn = display_field_function
                else:
                    display_field_function_fn = sync_to_async(
                        display_field_function
                    )

                obj_dict[field_name] = await display_field_function_fn(obj)

            return obj_dict

    async def serialize_obj_attributes(
        self,
        obj: Any,
        attributes_to_serizalize: list[ModelFieldWidgetSchema],
        session: AsyncSession,
    ) -> dict[str, Any]:
        """Serialize ORM model obj attribute to dict."""
        serialized_dict = {}

        for field in attributes_to_serizalize:
            try:
                serialized_dict[field.name] = getattr(obj, field.column_name)
            except DetachedInstanceError:
                obj = await session.merge(obj)
                serialized_dict[field.name] = getattr(obj, field.column_name)

        if inspect.iscoroutinefunction(obj.__str__):
            str_fn = obj.__str__
        else:
            str_fn = sync_to_async(obj.__str__)

        try:
            serialized_dict["__str__"] = await str_fn()
        except DetachedInstanceError:
            raise RuntimeError(
                "Object is detached from the session, and __str__ cannot be resolved."
            )

        return serialized_dict`
